lahzadi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, add_product_entry_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product-entry', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    stock = models.IntegerField()
    size = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "stock", "size"]

        def clean_name(self):
            name = self.cleaned_data["name"]
            return strip_tags(name)

        def clean_description(self):
            description = self.cleaned_data["description"]
            return strip_tags(description)
        
        def clean_price(self):
            price = self.cleaned_data["price"]
            return strip_tags(price)
        
        def clean_stock(self):
            stock = self.cleaned_data["stock"]
            return strip_tags(stock)
        
        def clean_size(self):
            size = self.cleaned_data["size"]
            return strip_tags(size)

main/views.py
from django.shortcuts import render, redirect, reverse
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime, json
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

@login_required(login_url='/login')
def show_main(request):
    context = {
        'name': request.user.username,
        'kelas' : 'PBP C',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product_entry(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product_entry = form.save(commit=False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_product_entry.html", context)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
      else:
        messages.error(request, "Invalid username or password. Please try again.")

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    product = Product.objects.get(pk = id)
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = Product.objects.get(pk = id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_entry_ajax(request):
    name = strip_tags(request.POST.get("name"))
    description = strip_tags(request.POST.get("description"))
    price = request.POST.get("price")
    stock = request.POST.get("stock")
    size = request.POST.get("size")
    user = request.user

    new_product = Product(
        name=name, description=description,
        price=price, stock=stock, size=size,
        user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            description=data["description"],
            stock=int(data["stock"]),
            size=int(data["size"]),
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_info.html
<div
    class="w-[375px] h-[375px] mb-6 bg-gradient-to-b from-[#D8B384] to-[#C3A084] rounded-xl overflow-hidden border border-[#5C4B3A] shadow-lg transition-transform transform hover:scale-105 hover:shadow-2xl">
    <div class="p-6 animate-shine">
        <h5 class="text-xl font-semibold text-[#5C4B3A] mb-2">{{ title }}</h5>
        <p class="text-lg text-[#F5E6CA] font-medium">{{ value }}</p>
    </div>
</div>

main/templates/card_product.html
<div
    class="max-w-sm mx-auto h-[375px] bg-white shadow-lg rounded-lg overflow-hidden transition transform hover:scale-105 hover:shadow-2xl flex flex-col justify-between">
    <div class="h-1 bg-gradient-to-r from-[#8B5E3C] via-[#D8B384] to-[#8B5E3C]"></div>
    <!-- Product Details Section -->
    <div class="p-6 flex-1">
        <h2 class="text-2xl font-bold text-[#5C4B3A] mb-2">{{ product_entry.name }}</h2>
        <p class="text-xl font-semibold text-[#8B5E3C] mb-2">Rp{{ product_entry.price }}</p>
        <p class="text-md text-[#6B5D53] mb-4">{{ product_entry.description|truncatechars:255 }}</p>
        <div class="text-sm text-[#5C4B3A]">
            <p><span class="font-bold">Stock:</span> {{ product_entry.stock }}</p>
            <p><span class="font-bold">Size:</span> {{ product_entry.size }} ml</p>
        </div>
    </div>

    <!-- Action Buttons (Edit and Delete) -->
    <div class="p-6 flex justify-between items-center">
        <!-- Edit Button -->
        <a href="{% url 'main:edit_product' product_entry.pk %}"
            class="flex items-center bg-[#8B5E3C] text-white py-2 px-4 rounded-lg hover:bg-[#5C4B3A] transition-all">
            <svg class="w-5 h-5 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 17l-5-5m0 0l5-5m-5 5h12">
                </path>
            </svg>
            Edit
        </a>

        <!-- Delete Button -->
        <a href="{% url 'main:delete_product' product_entry.pk %}"
            class="flex items-center bg-[#A3292F] text-white py-2 px-4 rounded-lg hover:bg-red-600 transition-all">
            <svg class="w-5 h-5 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
            Delete
        </a>
    </div>
</div>

main/templates/create_product_entry.html
{% extends 'base.html' %}
{% block content %}
<h1>Add New Product Entry</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product Entry" />
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Product - LAHZADI</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="min-h-screen bg-gradient-to-b from-stone-100 to-stone-200 flex items-center justify-center px-4 py-12">
    <div class="max-w-3xl w-full bg-white shadow-2xl rounded-lg overflow-hidden">
        <div class="bg-[#8B5E3C] px-6 py-4">
            <h1 class="text-2xl text-white text-center">Edit Product</h1>
        </div>

        <div class="p-8">
            <form method="POST" class="space-y-6">
                {% csrf_token %}
                {% for field in form %}
                <div class="mb-6">
                    <label for="{{ field.id_for_label }}" class="block text-sm font-medium text-gray-700 mb-2">
                        {{ field.label }}
                    </label>
                    <div class="mt-1">
                        {{ field }}
                    </div>
                    {% if field.help_text %}
                    <p class="mt-2 text-sm text-gray-500">{{ field.help_text }}</p>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="mt-8">
                    <button type="submit"
                        class="w-full bg-[#8B5E3C] text-white text-lg py-3 px-4 rounded-md hover:bg-[#7A5C49] transition duration-300 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#8B5E3C]">
                        Add to Collection
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
    input,
    textarea,
    select {
        width: 100%;
        padding: 0.5rem 0.75rem;
        background-color: #faf7f5;
        border: 1px solid #d3b8a3;
        line-height: 1.5;
    }

    input:focus,
    textarea:focus,
    select:focus {
        outline: none;
        border-color: #8B5E3C;
        background-color: #ffffff;
    }
</style>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
<link rel="stylesheet" href="styles.css">
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex">
    <!-- Left Side (Login Form) -->
    <div class="flex flex-col justify-center w-1/2 bg-white p-10">
        <div class="space-y-8">
            <!-- Welcome Sign -->
            <div>
                <h1 class="text-5xl font-extrabold text-[#97704f] text-center">
                    Welcome to <span class="text-[#5C4B3A]">LAHZADI!</span>
                </h1>
            </div>

            <!-- Login Form -->
            <form class="space-y-6" method="POST" action="">
                {% csrf_token %}
                <div class="space-y-4">
                    <!-- Username Input -->
                    <div>
                        <label for="email" class="block text-sm font-medium text-[#5C4B3A]">Username</label>
                        <input id="username" name="username" type="text" required
                            class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                            placeholder="Username">
                    </div>

                    <!-- Password Input -->
                    <div>
                        <label for="password" class="block text-sm font-medium text-[#5C4B3A]">Password</label>
                        <input id="password" name="password" type="password" required
                            class="block w-full px-4 py-2 mt-1 border border-[#C3A084] rounded-md text-[#5C4B3A] focus:outline-none focus:ring-2 focus:ring-[#97704f] focus:border-[#97704f]"
                            placeholder="Password">
                    </div>
                </div>

                <!-- Buttons (Login and Signup) -->
                <div class="flex space-x-4">
                    <button type="submit"
                        class="w-full bg-[#97704f] text-[#F5E6CA] text-center font-bold py-2 px-4 rounded-md hover:bg-[#7A5C49]">
                        Login
                    </button>
                    <a href="{% url 'main:register' %}"
                        class="w-full bg-[#C3A084] text-[#F5E6CA] text-center font-bold py-2 px-4 rounded-md hover:bg-[#A8866C] flex justify-center items-center">
                        Sign up
                    </a>
                </div>
            </form>
        </div>
    </div>

    <!-- Right Side (Decorative Section) -->
    <div class="w-1/2 bg-gradient-to-br from-[#D8B384] via-[#5C4B3A] to-[#97704f] flex items-center justify-center">
        <div class="text-white">
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>LAHZADI</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-8 min-h-screen bg-[#F4F1EB] flex flex-col">
    <div class="px-3 mb-4">
        <div class="flex justify-end py-2 px-4 text-[#5C4B3A] text-center">
            Last Login: {{last_login}}
        </div>
        <div class="flex justify-end mb-6 space-x-4">
            <a href="{% url 'main:create_product_entry' %}"
                class="bg-[#5C4B3A] hover:bg-[#97704f] text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
                Add New Product
            </a>
            <button data-modal-target="crudModal" data-modal-toggle="crudModal"
                class="btn bg-[#5C4B3A] hover:bg-[#97704f] text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105"
                onclick="showModal();">
                Add New Product by AJAX
            </button>
        </div>

        <div id="product_entry_cards"></div>
        <div id="crudModal" tabindex="-1" aria-hidden="true"
            class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
            <div id="crudModalContent"
                class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
                <!-- Modal header -->
                <div class="flex items-center justify-between p-4 border-b rounded-t">
                    <h3 class="text-xl font-semibold text-gray-900">
                        Add New Product
                    </h3>
                    <button type="button"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center"
                        id="closeModalBtn">
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                clip-rule="evenodd"></path>
                        </svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                </div>

                <!-- Modal body -->
                <div class="px-6 py-4 space-y-6 form-style">
                    <form id="productEntryForm">
                        <div class="mb-4">
                            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
                            <input type="text" id="name" name="name"
                                class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-[#8B5E3C]-700"
                                placeholder="Enter product name" required>
                        </div>
                        <div class="mb-4">
                            <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
                            <textarea id="description" name="description" rows="3"
                                class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-[#8B5E3C]-700"
                                placeholder="Describe your product" required></textarea>
                        </div>
                        <div class="mb-4">
                            <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
                            <input type="number" id="price" name="price" min="1"
                                class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-[#8B5E3C]-700"
                                placeholder="Enter product price" required>
                        </div>
                        <div class="mb-4">
                            <label for="stock" class="block text-sm font-medium text-gray-700">Stock</label>
                            <input type="number" id="stock" name="stock" min="1"
                                class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-[#8B5E3C]-700"
                                placeholder="Enter stock amount" required>
                        </div>
                        <div class="mb-4">
                            <label for="size" class="block text-sm font-medium text-gray-700">Size (ml)</label>
                            <input type="number" id="size" name="size" min="1"
                                class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-[#8B5E3C]-700"
                                placeholder="Enter product size" required>
                        </div>
                    </form>
                </div>

                <!-- Modal footer -->
                <div
                    class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
                    <button type="button"
                        class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg"
                        id="cancelButton">Cancel</button>
                    <button type="submit" id="submitProductEntry" form="productEntryForm"
                        class="bg-[#8B5E3C] hover:bg-[#8B5E3C] text-white font-bold py-2 px-4 rounded-lg">Save</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    async function getProductEntries() {
        return fetch("{% url 'main:show_json' %}").then((res) => res.json());
    }

    async function refreshProductEntries() {
        document.getElementById("product_entry_cards").innerHTML = "";
        document.getElementById("product_entry_cards").className = "";
        const productEntries = await getProductEntries();
        let htmlString = "";
        let classNameString = "";

        if (productEntries.length === 0) {
            classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
            htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <img src="{% static 'image/sedih-banget.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
                <p class="text-center text-gray-600 mt-4">Belum ada data produk di web ini.</p>
            </div>
        `;
        } else {
            classNameString = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full";
            productEntries.forEach((item) => {
                const name = DOMPurify.sanitize(item.fields.name);
                const description = DOMPurify.sanitize(item.fields.description);
                const price = DOMPurify.sanitize(item.fields.price);
                const stock = DOMPurify.sanitize(item.fields.stock);
                const size = DOMPurify.sanitize(item.fields.size);
                htmlString += `
                <div class="max-w-sm mx-auto w-[375px] h-[375px] bg-white shadow-lg rounded-lg overflow-hidden transition transform hover:scale-105 hover:shadow-2xl flex flex-col justify-between mb-6">
                    <div class="h-1 bg-gradient-to-r from-[#8B5E3C] via-[#D8B384] to-[#8B5E3C]"></div>
                    <div class="p-6 flex-1">
                        <h2 class="text-2xl font-bold text-[#5C4B3A] mb-2">${name}</h2>
                        <p class="text-xl font-semibold text-[#8B5E3C] mb-2">Rp${price}</p>
                        <p class="text-md text-[#6B5D53] mb-4">${description}</p>
                        <div class="text-sm text-[#5C4B3A]">
                            <p><span class="font-bold">Stock:</span> ${stock}</p>
                            <p><span class="font-bold">Size:</span> ${size} ml</p>
                        </div>
                    </div>

                    <div class="p-6 flex justify-between items-center">
                        <a href="/edit-product/${item.pk}" 
                            class="flex items-center bg-[#8B5E3C] text-white py-2 px-4 rounded-lg hover:bg-[#5C4B3A] transition-all">
                            <svg class="w-5 h-5 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 17l-5-5m0 0l5-5m-5 5h12"></path>
                            </svg>
                            Edit
                        </a>

                        <a href="/delete/${item.pk}"
                            class="flex items-center bg-[#A3292F] text-white py-2 px-4 rounded-lg hover:bg-red-600 transition-all">
                            <svg class="w-5 h-5 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                            </svg>
                            Delete
                        </a>
                    </div>
                </div>
            `;
            });
        }

        document.getElementById("product_entry_cards").className = classNameString;
        document.getElementById("product_entry_cards").innerHTML = htmlString;
    }

    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    function showModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modal.classList.remove('hidden');
        setTimeout(() => {
            modalContent.classList.remove('opacity-0', 'scale-95');
            modalContent.classList.add('opacity-100', 'scale-100');
        }, 50);
    }

    function hideModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modalContent.classList.remove('opacity-100', 'scale-100');
        modalContent.classList.add('opacity-0', 'scale-95');

        setTimeout(() => {
            modal.classList.add('hidden');
        }, 150);
    }

    document.getElementById("cancelButton").addEventListener("click", hideModal);
    document.getElementById("closeModalBtn").addEventListener("click", hideModal);
    refreshProductEntries();

    function addProductEntry() {
        fetch("{% url 'main:add_product_entry_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#productEntryForm')),
        })
            .then(response => refreshProductEntries())

        document.getElementById("productEntryForm").reset();
        document.querySelector("[data-modal-toggle='crudModal']").click();

        return false;
    }

    document.getElementById("productEntryForm").addEventListener("submit", (e) => {
        e.preventDefault();
        addProductEntry();
    })
</script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-[#F5E6CA] py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8 form-style">
        <div>
            <h1 class="mt-6 text-center text-3xl font-extrabold text-[#8B5E3C]">
                Create Account
            </h1>
        </div>
        <form class="mt-8 space-y-6" method="POST">
            {% csrf_token %}
            <input type="hidden" name="remember" value="true">
            <div class="rounded-md shadow-sm -space-y-px">
                {% for field in form %}
                <div class="{% if not forloop.first %}mt-4{% endif %}">
                    <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-[#5C4B3A]">
                        {{ field.label }}
                    </label>
                    <div class="relative">
                        {{ field }}
                        <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                            {% if field.errors %}
                            <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd"
                                    d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z"
                                    clip-rule="evenodd" />
                            </svg>
                            {% endif %}
                        </div>
                    </div>
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                    {% endfor %}
                    {% endif %}
                </div>
                {% endfor %}
            </div>

            <div>
                <button type="submit"
                    class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-[#F5E6CA] bg-[#97704f] hover:[#CCAA85] focus:outline-none focus:ring-[#97704f] focus:ring-offset-2 focus:[#B08C67]">
                    Register
                </button>
            </div>
        </form>

        {% if messages %}
        <div class="mt-4">
            {% for message in messages %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <div class="text-center mt-4">
            <p class="text-sm text-[#5C4B3A]">
                Already have an account?
                <a href="{% url 'main:login' %}" class="font-medium text-[#97704f] hover:[#CCAA85]">
                    Login here
                </a>
            </p>
        </div>
    </div>
</div>
{% endblock content %}